countd0_1 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D0_contrast1_0out.rds'))
countd0_2 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D0_contrast2_0out.rds'))
countd0_3 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D0_contrast3_0out.rds'))
countd0_4 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D0_contrast4_0out.rds'))
countd0_5 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D0_contrast5_0out.rds'))
countd0_6 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D0_contrast6_0out.rds'))

dim(countd0_1)
dim(countd0_2)
dim(countd0_3)
dim(countd0_4)
dim(countd0_5)
dim(countd0_6)

rm(list = ls())

countD8_1 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D8_contrast1_0out.rds'))
countD8_2 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D8_contrast2_0out.rds'))
countD8_3 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D8_contrast3_0out.rds'))
countD8_4 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D8_contrast4_0out.rds'))
countD8_5 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D8_contrast5_0out.rds'))
countD8_6 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D8_contrast6_0out.rds'))

dim(countD8_1)
dim(countD8_2)
dim(countD8_3)
dim(countD8_4)
dim(countD8_5)
dim(countD8_6)

rm(list = ls())

countD28_1 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D28_contrast1_0out.rds'))
countD28_2 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D28_contrast2_0out.rds'))
countD28_3 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D28_contrast3_0out.rds'))
countD28_4 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D28_contrast4_0out.rds'))
countD28_5 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D28_contrast5_0out.rds'))
countD28_6 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D28_contrast6_0out.rds'))

dim(countD28_1)
dim(countD28_2)
dim(countD28_3)
dim(countD28_4)
dim(countD28_5)
dim(countD28_6)

rm(list = ls())

countD42_1 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D42_contrast1_0out.rds'))
countD42_2 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D42_contrast2_0out.rds'))
countD42_3 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D42_contrast3_0out.rds'))
countD42_4 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D42_contrast4_0out.rds'))
countD42_5 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D42_contrast5_0out.rds'))
countD42_6 <- readRDS(file = here('data', 'clean', 'merged_gene_abundance_D42_contrast6_0out.rds'))

dim(countD42_1)
dim(countD42_2)
dim(countD42_3)
dim(countD42_4)
dim(countD42_5)
dim(countD42_6)

metaD42_1 <- readRDS(file = here('data', 'clean', 'metaD42_contrast1_0out.rds'))
metaD42_2 <- readRDS(file = here('data', 'clean', 'metaD42_contrast2_0out.rds'))
metaD42_3 <- readRDS(file = here('data', 'clean', 'metaD42_contrast3_0out.rds'))
metaD42_4 <- readRDS(file = here('data', 'clean', 'metaD42_contrast4_0out.rds'))
metaD42_5 <- readRDS(file = here('data', 'clean', 'metaD42_contrast5_0out.rds'))
metaD42_6 <- readRDS(file = here('data', 'clean', 'metaD42_contrast6_0out.rds'))

